
Imports BL

Public Class SelectDyeingProg

    Public PARTYNAME As String = ""
    Public DELIVERYAT As String = ""
    Public PROGNO As Integer = 0
    Public DT As New DataTable

    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub SelectYarnPO_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode =System.WINDOWS.FORMS.Keys.Escape Then
            Me.Close()
        ElseIf e.KeyCode = Keys.Enter Then
            SendKeys.Send("{Tab}")
        End If
    End Sub

    Private Sub SelectYarnPO_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        fillgrid()
    End Sub

    Sub fillgrid()
        Try
            Cursor.Current = Cursors.WaitCursor

            Dim where As String = ""
            If PROGNO <> 0 Then where = where & " AND PROGNO = " & PROGNO
            If PARTYNAME <> "" Then where = where & " AND NAME = '" & PARTYNAME & "'"
            If DELIVERYAT <> "" Then where = where & " AND DELIVERYAT = '" & DELIVERYAT & "'"
            Dim OBJCMN As New ClsCommon()
            Dim dt As DataTable = OBJCMN.search("*", "", "(SELECT YARNDYEINGPROGRAM.PROG_NO AS PROGNO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, YARNDYEINGPROGRAM.PROG_DATE AS DATE, YARNDYEINGPROGRAM_DESC.PROG_GRIDSRNO AS GRIDSRNO, ISNULL(YARNQUALITYMASTER.YARN_name, '') AS YARNQUALITY, ISNULL(MILLMASTER.MILL_NAME, '') AS MILLNAME, ISNULL(YARNDYEINGPROGRAM_DESC.PROG_DESC, '') AS GRIDREMARKS, ISNULL(COLORMASTER.COLOR_name, '') AS COLOR, (YARNDYEINGPROGRAM_DESC.PROG_BAGS - YARNDYEINGPROGRAM_DESC.PROG_RECDBAGS) AS BAGS, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ROUND(YARNDYEINGPROGRAM_DESC.PROG_WT - YARNDYEINGPROGRAM_DESC.PROG_RECDWT, 2) AS WT, YARNDYEINGPROGRAM.PROG_DUEDATE AS DUEDATE, ISNULL(GROUPMASTER.group_name, '') AS GROUPNAME, ISNULL(YARNDYEINGPROGRAM_DESC.PROG_RATE, 0) AS RATE, ISNULL(YARNDYEINGPROGRAM.PROG_REFNO, '') AS ORDERNO, 'YARNDYEINGPROGRAM' AS [TYPE], ISNULL(PROG_ORDERTYPE,'GREY') AS ORDERTYPE, ISNULL(GRIDLEDGERS.ACC_CMPNAME,'') AS DELIVERYAT, ISNULL(YARNDYEINGPROGRAM.PROG_REDYEING,0) AS REDYEING, ISNULL(SOURCEYARNQUALITYMASTER.YARN_name, '') AS SOURCEYARNQUALITY,  ISNULL(SOURCECOLORMASTER.COLOR_name, '') AS SOURCECOLOR FROM YARNDYEINGPROGRAM INNER JOIN YARNDYEINGPROGRAM_DESC ON YARNDYEINGPROGRAM.PROG_YEARID = YARNDYEINGPROGRAM_DESC.PROG_YEARID AND YARNDYEINGPROGRAM.PROG_NO = YARNDYEINGPROGRAM_DESC.PROG_NO INNER JOIN LEDGERS ON YARNDYEINGPROGRAM.PROG_LEDGERID = LEDGERS.Acc_id INNER JOIN GROUPMASTER ON LEDGERS.Acc_groupid = GROUPMASTER.group_id LEFT OUTER JOIN UNITMASTER ON YARNDYEINGPROGRAM_DESC.PROG_UNITID = UNITMASTER.unit_id LEFT OUTER JOIN COLORMASTER ON YARNDYEINGPROGRAM_DESC.PROG_SHADEID = COLORMASTER.COLOR_id LEFT OUTER JOIN YARNQUALITYMASTER ON YARNDYEINGPROGRAM_DESC.PROG_YARNQUALITYID = YARNQUALITYMASTER.YARN_id LEFT OUTER JOIN MILLMASTER ON YARNDYEINGPROGRAM_DESC.PROG_MILLID = MILLMASTER.MILL_ID LEFT OUTER JOIN LEDGERS AS GRIDLEDGERS ON YARNDYEINGPROGRAM_DESC.PROG_GRIDLEDGERID = GRIDLEDGERS.ACC_id LEFT OUTER JOIN COLORMASTER AS SOURCECOLORMASTER ON YARNDYEINGPROGRAM.PROG_FROMSHADEID= SOURCECOLORMASTER.COLOR_id LEFT OUTER JOIN YARNQUALITYMASTER AS SOURCEYARNQUALITYMASTER ON YARNDYEINGPROGRAM.PROG_FROMYARNQUALITYID = SOURCEYARNQUALITYMASTER.YARN_id WHERE YARNDYEINGPROGRAM_DESC.PROG_CLOSED='False' AND ROUND(YARNDYEINGPROGRAM_DESC.PROG_WT - YARNDYEINGPROGRAM_DESC.PROG_RECDWT,2) > 0 AND YARNDYEINGPROGRAM.PROG_YEARID = " & YearId & " UNION ALL SELECT OPENINGYARNDYEINGPROGRAM.PROG_NO AS PONO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, OPENINGYARNDYEINGPROGRAM.PROG_DATE AS DATE, OPENINGYARNDYEINGPROGRAM_DESC.PROG_GRIDSRNO AS GRIDSRNO, ISNULL(YARNQUALITYMASTER.YARN_name, '') AS YARNQUALITY, ISNULL(MILLMASTER.MILL_NAME, '') AS MILLNAME, ISNULL(OPENINGYARNDYEINGPROGRAM_DESC.PROG_DESC, '') AS GRIDREMARKS, ISNULL(COLORMASTER.COLOR_name, '') AS COLOR, (OPENINGYARNDYEINGPROGRAM_DESC.PROG_BAGS - OPENINGYARNDYEINGPROGRAM_DESC.PROG_RECDBAGS) AS BAGS, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ROUND(OPENINGYARNDYEINGPROGRAM_DESC.PROG_WT - OPENINGYARNDYEINGPROGRAM_DESC.PROG_RECDWT, 2) AS WT, OPENINGYARNDYEINGPROGRAM.PROG_DUEDATE AS DUEDATE, ISNULL(GROUPMASTER.group_name, '') AS GROUPNAME, ISNULL(OPENINGYARNDYEINGPROGRAM_DESC.PROG_RATE, 0) AS RATE, ISNULL(OPENINGYARNDYEINGPROGRAM.PROG_REFNO, '') AS ORDERNO, 'OPENING' AS [TYPE] , ISNULL(PROG_ORDERTYPE,'GREY') AS ORDERTYPE, ISNULL(GRIDLEDGERS.ACC_CMPNAME,'') AS DELIVERYAT, ISNULL(OPENINGYARNDYEINGPROGRAM.PROG_REDYEING,0) AS REDYEING, ISNULL(SOURCEYARNQUALITYMASTER.YARN_name, '') AS SOURCEYARNQUALITY,  ISNULL(SOURCECOLORMASTER.COLOR_name, '') AS SOURCECOLOR FROM OPENINGYARNDYEINGPROGRAM INNER JOIN OPENINGYARNDYEINGPROGRAM_DESC ON OPENINGYARNDYEINGPROGRAM.PROG_YEARID = OPENINGYARNDYEINGPROGRAM_DESC.PROG_YEARID AND OPENINGYARNDYEINGPROGRAM.PROG_NO = OPENINGYARNDYEINGPROGRAM_DESC.PROG_NO INNER JOIN LEDGERS ON OPENINGYARNDYEINGPROGRAM.PROG_LEDGERID = LEDGERS.Acc_id INNER JOIN GROUPMASTER ON LEDGERS.Acc_groupid = GROUPMASTER.group_id LEFT OUTER JOIN UNITMASTER ON OPENINGYARNDYEINGPROGRAM_DESC.PROG_UNITID = UNITMASTER.unit_id LEFT OUTER JOIN COLORMASTER ON OPENINGYARNDYEINGPROGRAM_DESC.PROG_SHADEID = COLORMASTER.COLOR_id LEFT OUTER JOIN YARNQUALITYMASTER ON OPENINGYARNDYEINGPROGRAM_DESC.PROG_YARNQUALITYID = YARNQUALITYMASTER.YARN_id  LEFT OUTER JOIN MILLMASTER ON OPENINGYARNDYEINGPROGRAM_DESC.PROG_MILLID = MILLMASTER.MILL_ID LEFT OUTER JOIN LEDGERS AS GRIDLEDGERS ON OPENINGYARNDYEINGPROGRAM_DESC.PROG_GRIDLEDGERID = GRIDLEDGERS.ACC_id LEFT OUTER JOIN COLORMASTER AS SOURCECOLORMASTER ON OPENINGYARNDYEINGPROGRAM.PROG_FROMSHADEID= SOURCECOLORMASTER.COLOR_id LEFT OUTER JOIN YARNQUALITYMASTER AS SOURCEYARNQUALITYMASTER ON OPENINGYARNDYEINGPROGRAM.PROG_FROMYARNQUALITYID = SOURCEYARNQUALITYMASTER.YARN_id WHERE OPENINGYARNDYEINGPROGRAM_DESC.PROG_CLOSED='False' AND ROUND(OPENINGYARNDYEINGPROGRAM_DESC.PROG_WT - OPENINGYARNDYEINGPROGRAM_DESC.PROG_RECDWT,2) > 0 AND OPENINGYARNDYEINGPROGRAM.PROG_YEARID = " & YearId & ") AS T", where & " order by T.DATE, T.PROGNO")
            'Dim dt As DataTable = OBJCMN.search("*", "", "(SELECT YARNDYEINGPROGRAM.PROG_NO AS PROGNO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, YARNDYEINGPROGRAM.PROG_DATE AS DATE, YARNDYEINGPROGRAM_DESC.PROG_GRIDSRNO AS GRIDSRNO, ISNULL(YARNQUALITYMASTER.YARN_name, '') AS YARNQUALITY,  ISNULL(COLORMASTER.COLOR_name, '') AS COLOR, ROUND(YARNDYEINGPROGRAM_DESC.PROG_WT - YARNDYEINGPROGRAM_DESC.PROG_RECDWT, 2) AS WT, 'YARNDYEINGPROGRAM' AS [TYPE], ISNULL(GRIDLEDGERS.ACC_CMPNAME,'') AS DELIVERYAT, ISNULL(YARNDYEINGPROGRAM.PROG_REDYEING,0) AS REDYEING, ISNULL(SOURCEYARNQUALITYMASTER.YARN_name, '') AS SOURCEYARNQUALITY,  ISNULL(SOURCECOLORMASTER.COLOR_name, '') AS SOURCECOLOR  FROM YARNDYEINGPROGRAM INNER JOIN YARNDYEINGPROGRAM_DESC ON YARNDYEINGPROGRAM.PROG_YEARID = YARNDYEINGPROGRAM_DESC.PROG_YEARID AND YARNDYEINGPROGRAM.PROG_NO = YARNDYEINGPROGRAM_DESC.PROG_NO INNER JOIN LEDGERS ON YARNDYEINGPROGRAM.PROG_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN COLORMASTER ON YARNDYEINGPROGRAM_DESC.PROG_SHADEID= COLORMASTER.COLOR_id LEFT OUTER JOIN YARNQUALITYMASTER ON YARNDYEINGPROGRAM_DESC.PROG_YARNQUALITYID = YARNQUALITYMASTER.YARN_id LEFT OUTER JOIN COLORMASTER AS SOURCECOLORMASTER ON YARNDYEINGPROGRAM.PROG_FROMSHADEID= SOURCECOLORMASTER.COLOR_id LEFT OUTER JOIN YARNQUALITYMASTER AS SOURCEYARNQUALITYMASTER ON YARNDYEINGPROGRAM.PROG_FROMYARNQUALITYID = SOURCEYARNQUALITYMASTER.YARN_id LEFT OUTER JOIN LEDGERS AS GRIDLEDGERS ON YARNDYEINGPROGRAM_DESC.PROG_GRIDLEDGERID = GRIDLEDGERS.ACC_ID WHERE YARNDYEINGPROGRAM_DESC.PROG_CLOSED='False' AND ROUND(YARNDYEINGPROGRAM_DESC.PROG_WT - YARNDYEINGPROGRAM_DESC.PROG_RECDWT,2) > 0 AND YARNDYEINGPROGRAM.PROG_YEARID = " & YearId & " UNION ALL SELECT OPENINGYARNDYEINGPROGRAM.PROG_NO AS PROGNO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, OPENINGYARNDYEINGPROGRAM.PROG_DATE AS DATE, OPENINGYARNDYEINGPROGRAM_DESC.PROG_GRIDSRNO AS GRIDSRNO, ISNULL(YARNQUALITYMASTER.YARN_name, '') AS YARNQUALITY,  ISNULL(COLORMASTER.COLOR_name, '') AS COLOR, ROUND(OPENINGYARNDYEINGPROGRAM_DESC.PROG_WT - OPENINGYARNDYEINGPROGRAM_DESC.PROG_RECDWT, 2) AS WT, 'OPENING' AS [TYPE], ISNULL(GRIDLEDGERS.ACC_CMPNAME,'') AS DELIVERYAT, ISNULL(OPENINGYARNDYEINGPROGRAM.PROG_REDYEING,0) AS REDYEING, ISNULL(SOURCEYARNQUALITYMASTER.YARN_name, '') AS SOURCEYARNQUALITY,  ISNULL(SOURCECOLORMASTER.COLOR_name, '') AS SOURCECOLOR FROM OPENINGYARNDYEINGPROGRAM INNER JOIN OPENINGYARNDYEINGPROGRAM_DESC ON OPENINGYARNDYEINGPROGRAM.PROG_YEARID = OPENINGYARNDYEINGPROGRAM_DESC.PROG_YEARID AND OPENINGYARNDYEINGPROGRAM.PROG_NO = OPENINGYARNDYEINGPROGRAM_DESC.PROG_NO INNER JOIN LEDGERS ON OPENINGYARNDYEINGPROGRAM.PROG_LEDGERID = LEDGERS.Acc_id LEFT OUTER JOIN COLORMASTER ON OPENINGYARNDYEINGPROGRAM_DESC.PROG_SHADEID= COLORMASTER.COLOR_id LEFT OUTER JOIN YARNQUALITYMASTER ON OPENINGYARNDYEINGPROGRAM_DESC.PROG_YARNQUALITYID = YARNQUALITYMASTER.YARN_id  LEFT OUTER JOIN COLORMASTER AS SOURCECOLORMASTER ON OPENINGYARNDYEINGPROGRAM.PROG_FROMSHADEID= SOURCECOLORMASTER.COLOR_id LEFT OUTER JOIN YARNQUALITYMASTER AS SOURCEYARNQUALITYMASTER ON OPENINGYARNDYEINGPROGRAM.PROG_FROMYARNQUALITYID = SOURCEYARNQUALITYMASTER.YARN_id LEFT OUTER JOIN LEDGERS AS GRIDLEDGERS ON OPENINGYARNDYEINGPROGRAM_DESC.PROG_GRIDLEDGERID = GRIDLEDGERS.ACC_ID WHERE OPENINGYARNDYEINGPROGRAM_DESC.PROG_CLOSED='False' AND ROUND(OPENINGYARNDYEINGPROGRAM_DESC.PROG_WT - OPENINGYARNDYEINGPROGRAM_DESC.PROG_RECDWT,2) > 0 AND OPENINGYARNDYEINGPROGRAM.PROG_YEARID = " & YearId & ") AS T", where & " order by T.DATE, T.PROGNO")
            gridbilldetails.DataSource = dt
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        Finally
            Cursor.Current = Cursors.Default

        End Try
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click
        Try

            DT.Columns.Add("PROGNO")
            DT.Columns.Add("NAME")
            DT.Columns.Add("PROGDATE")
            DT.Columns.Add("GRIDSRNO")
            DT.Columns.Add("YARNQUALITY")
            DT.Columns.Add("COLOR")
            DT.Columns.Add("WT")
            DT.Columns.Add("TYPE")
            DT.Columns.Add("REDYEING")
            DT.Columns.Add("SOURCEYARNQUALITY")
            DT.Columns.Add("SOURCECOLOR")

            Dim SELECTEDROWS As Int32() = gridbill.GetSelectedRows()
            For I As Integer = 0 To Val(SELECTEDROWS.Length - 1)
                Dim dtrow As DataRow = gridbill.GetDataRow(SELECTEDROWS(I))
                DT.Rows.Add(dtrow("PROGNO"), dtrow("NAME"), dtrow("DATE"), Val(dtrow("GRIDSRNO")), dtrow("YARNQUALITY"), dtrow("COLOR"), Val(dtrow("WT")), dtrow("TYPE"), dtrow("REDYEING"), dtrow("SOURCEYARNQUALITY"), dtrow("SOURCECOLOR"))
            Next
            Me.Close()

        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub gridquotation_CellDoubleClick(ByVal sender As Object, ByVal e As System.Windows.Forms.DataGridViewCellEventArgs)
        Try
            cmdok_Click(sender, e)
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

End Class