
Imports BL

Public Class SelectYarnPO

    Public PARTYNAME As String = ""
    Public DELIVERYAT As String = ""
    Public PONO As Integer = 0
    Public DT As New DataTable

    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub SelectYarnPO_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode =System.WINDOWS.FORMS.Keys.Escape Then
            Me.Close()
        ElseIf e.KeyCode = Keys.Enter Then
            SendKeys.Send("{Tab}")
        End If
    End Sub

    Private Sub SelectYarnPO_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        fillgrid()
    End Sub

    Sub fillgrid()
        Try
            Cursor.Current = Cursors.WaitCursor

            Dim where As String = ""
            If PONO <> 0 Then where = where & " AND PONO = " & PONO
            If PARTYNAME <> "" Then where = where & " AND NAME = '" & PARTYNAME & "'"
            If DELIVERYAT <> "" Then where = where & " AND DELIVERYAT = '" & DELIVERYAT & "'"
            Dim objclspreq As New ClsCommon()
            Dim dt As DataTable = objclspreq.search("*", "", " (SELECT YARNPURCHASEORDER.YPO_NO AS PONO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, YARNPURCHASEORDER.YPO_DATE AS DATE, YARNPURCHASEORDER_DESC.YPO_GRIDSRNO AS GRIDSRNO, ISNULL(YARNQUALITYMASTER.YARN_name, '') AS YARNQUALITY, ISNULL(MILLMASTER.MILL_NAME, '') AS MILLNAME, ISNULL(YARNPURCHASEORDER_DESC.YPO_DESC, '') AS GRIDREMARKS, ISNULL(COLORMASTER.COLOR_name, '') AS COLOR, (YARNPURCHASEORDER_DESC.YPO_BAGS - YARNPURCHASEORDER_DESC.YPO_RECDBAGS) AS BAGS, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ROUND(YARNPURCHASEORDER_DESC.YPO_WT - YARNPURCHASEORDER_DESC.YPO_RECDWT, 2) AS WT, YARNPURCHASEORDER.YPO_DUEDATE AS DUEDATE, ISNULL(GROUPMASTER.group_name, '') AS GROUPNAME, ISNULL(YARNPURCHASEORDER_DESC.YPO_RATE, 0) AS RATE, ISNULL(YARNPURCHASEORDER.YPO_REFNO, '') AS ORDERNO, 'YARNPURCHASEORDER' AS [TYPE], ISNULL(YPO_ORDERTYPE,'GREY') AS ORDERTYPE, ISNULL(GRIDLEDGERS.ACC_CMPNAME,'') AS DELIVERYAT FROM YARNPURCHASEORDER INNER JOIN YARNPURCHASEORDER_DESC ON YARNPURCHASEORDER.YPO_YEARID = YARNPURCHASEORDER_DESC.YPO_YEARID AND YARNPURCHASEORDER.YPO_NO = YARNPURCHASEORDER_DESC.YPO_NO INNER JOIN LEDGERS ON YARNPURCHASEORDER.YPO_LEDGERID = LEDGERS.Acc_id INNER JOIN GROUPMASTER ON LEDGERS.Acc_groupid = GROUPMASTER.group_id LEFT OUTER JOIN UNITMASTER ON YARNPURCHASEORDER_DESC.YPO_UNITID = UNITMASTER.unit_id LEFT OUTER JOIN COLORMASTER ON YARNPURCHASEORDER_DESC.YPO_SHADEID = COLORMASTER.COLOR_id LEFT OUTER JOIN YARNQUALITYMASTER ON YARNPURCHASEORDER_DESC.YPO_YARNQUALITYID = YARNQUALITYMASTER.YARN_id LEFT OUTER JOIN MILLMASTER ON YARNPURCHASEORDER_DESC.YPO_MILLID = MILLMASTER.MILL_ID LEFT OUTER JOIN LEDGERS AS GRIDLEDGERS ON YARNPURCHASEORDER_DESC.YPO_GRIDLEDGERID = GRIDLEDGERS.ACC_id WHERE YARNPURCHASEORDER_DESC.YPO_CLOSED='False' AND ROUND(YARNPURCHASEORDER_DESC.YPO_WT - YARNPURCHASEORDER_DESC.YPO_RECDWT,2) > 0 AND YARNPURCHASEORDER.YPO_YEARID = " & YearId & " UNION ALL SELECT OPENINGYARNPURCHASEORDER.OYPO_NO AS PONO, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, OPENINGYARNPURCHASEORDER.OYPO_DATE AS DATE, OPENINGYARNPURCHASEORDER_DESC.OYPO_GRIDSRNO AS GRIDSRNO, ISNULL(YARNQUALITYMASTER.YARN_name, '') AS YARNQUALITY, ISNULL(MILLMASTER.MILL_NAME, '') AS MILLNAME, ISNULL(OPENINGYARNPURCHASEORDER_DESC.OYPO_DESC, '') AS GRIDREMARKS, ISNULL(COLORMASTER.COLOR_name, '') AS COLOR, (OPENINGYARNPURCHASEORDER_DESC.OYPO_BAGS - OPENINGYARNPURCHASEORDER_DESC.OYPO_RECDBAGS) AS BAGS, ISNULL(UNITMASTER.unit_abbr, '') AS UNIT, ROUND(OPENINGYARNPURCHASEORDER_DESC.OYPO_WT - OPENINGYARNPURCHASEORDER_DESC.OYPO_RECDWT, 2) AS WT, OPENINGYARNPURCHASEORDER.OYPO_DUEDATE AS DUEDATE, ISNULL(GROUPMASTER.group_name, '') AS GROUPNAME, ISNULL(OPENINGYARNPURCHASEORDER_DESC.OYPO_RATE, 0) AS RATE, ISNULL(OPENINGYARNPURCHASEORDER.OYPO_REFNO, '') AS ORDERNO, 'OPENING' AS [TYPE] , ISNULL(OYPO_ORDERTYPE,'GREY') AS ORDERTYPE, ISNULL(GRIDLEDGERS.ACC_CMPNAME,'') AS DELIVERYAT FROM OPENINGYARNPURCHASEORDER INNER JOIN OPENINGYARNPURCHASEORDER_DESC ON OPENINGYARNPURCHASEORDER.OYPO_YEARID = OPENINGYARNPURCHASEORDER_DESC.OYPO_YEARID AND OPENINGYARNPURCHASEORDER.OYPO_NO = OPENINGYARNPURCHASEORDER_DESC.OYPO_NO INNER JOIN LEDGERS ON OPENINGYARNPURCHASEORDER.OYPO_LEDGERID = LEDGERS.Acc_id INNER JOIN GROUPMASTER ON LEDGERS.Acc_groupid = GROUPMASTER.group_id LEFT OUTER JOIN UNITMASTER ON OPENINGYARNPURCHASEORDER_DESC.OYPO_UNITID = UNITMASTER.unit_id LEFT OUTER JOIN COLORMASTER ON OPENINGYARNPURCHASEORDER_DESC.OYPO_SHADEID = COLORMASTER.COLOR_id LEFT OUTER JOIN YARNQUALITYMASTER ON OPENINGYARNPURCHASEORDER_DESC.OYPO_YARNQUALITYID = YARNQUALITYMASTER.YARN_id  LEFT OUTER JOIN MILLMASTER ON OPENINGYARNPURCHASEORDER_DESC.OYPO_MILLID = MILLMASTER.MILL_ID LEFT OUTER JOIN LEDGERS AS GRIDLEDGERS ON OPENINGYARNPURCHASEORDER_DESC.OYPO_GRIDLEDGERID = GRIDLEDGERS.ACC_id WHERE OPENINGYARNPURCHASEORDER_DESC.OYPO_CLOSED='False' AND ROUND(OPENINGYARNPURCHASEORDER_DESC.OYPO_WT - OPENINGYARNPURCHASEORDER_DESC.OYPO_RECDWT,2) > 0 AND OPENINGYARNPURCHASEORDER.OYPO_YEARID = " & YearId & ") AS T", where & " order by T.DATE, T.PONO")
            gridbilldetails.DataSource = dt
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        Finally
            Cursor.Current = Cursors.Default

        End Try
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click
        Try

            DT.Columns.Add("PONO")
            DT.Columns.Add("NAME")
            DT.Columns.Add("PODATE")
            DT.Columns.Add("GRIDSRNO")
            DT.Columns.Add("YARNQUALITY")
            DT.Columns.Add("MILLNAME")
            DT.Columns.Add("COLOR")
            DT.Columns.Add("BAGS")
            DT.Columns.Add("WT")
            DT.Columns.Add("DUEDATE")
            DT.Columns.Add("GROUPNAME")
            DT.Columns.Add("RATE")
            DT.Columns.Add("TYPE")

            Dim SELECTEDROWS As Int32() = gridbill.GetSelectedRows()
            For I As Integer = 0 To Val(SELECTEDROWS.Length - 1)
                Dim dtrow As DataRow = gridbill.GetDataRow(SELECTEDROWS(I))
                DT.Rows.Add(dtrow("PONO"), dtrow("NAME"), dtrow("DATE"), Val(dtrow("GRIDSRNO")), dtrow("YARNQUALITY"), dtrow("MILLNAME"), dtrow("COLOR"), Val(dtrow("BAGS")), Val(dtrow("WT")), dtrow("DUEDATE"), dtrow("GROUPNAME"), Val(dtrow("RATE")), dtrow("TYPE"))
            Next
            Me.Close()

        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub gridquotation_CellDoubleClick(ByVal sender As Object, ByVal e As System.Windows.Forms.DataGridViewCellEventArgs)
        Try
            cmdok_Click(sender, e)
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

End Class