
Imports BL

Public Class SaleOrderVsStockGridReport

    Dim USERADD, USEREDIT, USERVIEW, USERDELETE As Boolean      'USED FOR RIGHT MANAGEMAENT
    Public WHERECLAUSE As String = ""
    Public OTHERWHERECLAUSE As String = ""
    Public SOCLAUSE As String = ""

    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub ExcelExport_Click(sender As Object, e As EventArgs) Handles ExcelExport.Click
        Try
            Try

                Dim PATH As String = Application.StartupPath & "\Order Details.XLS"
                Dim opti As New DevExpress.XtraPrinting.XlsExportOptions
                opti.ShowGridLines = True
                opti.SheetName = "Order Details"
                GRIDBILL.ExportToXls(PATH, opti)
                EXCELCMPHEADER(PATH, "Order Details", GRIDBILL.VisibleColumns.Count + GRIDBILL.GroupCount)
            Catch ex As Exception
                Throw ex
            End Try
        Catch ex As Exception
            MsgBox("Order Details Excel File is Open, Please Close the File first then try to Export", MsgBoxStyle.Critical)
        End Try
    End Sub

    Private Sub SaleOrderVsStockGridReport_KeyDown(sender As Object, e As KeyEventArgs) Handles Me.KeyDown
        Try
            If e.KeyCode =System.WINDOWS.FORMS.Keys.Escape Then
                Me.Close()
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub SaleOrderVsStockGridReport_Load(sender As Object, e As EventArgs) Handles Me.Load
        Try
            Dim DTROW() As DataRow
            DTROW = USERRIGHTS.Select("FormName = 'SALE ORDER'")
            USERADD = DTROW(0).Item(1)
            USEREDIT = DTROW(0).Item(2)
            USERVIEW = DTROW(0).Item(3)
            USERDELETE = DTROW(0).Item(4)

            If USEREDIT = False And USERVIEW = False Then
                MsgBox("Insufficient Rights")
                Exit Sub
            End If

            If ClientName <> "AVIS" Then GMILLNAME.Visible = False

            fillgrid()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub fillgrid()
        Try
            Dim OBJCMN As New ClsCommon
            'WITH THIS QUERY WE ARE NOT GETTING THOSE ITEMS WHOSE STOCK IS NOT THERE BUT ORDER IS PRESENT
            'Dim DT As DataTable = OBJCMN.search(" BARCODESTOCK.ITEMNAME, BARCODESTOCK.DESIGNNO, BARCODESTOCK.COLOR AS SHADE, ISNULL(T.ORDERPCS,0) AS ORDERPCS, ISNULL(T.ORDERMTRS,0) AS ORDERMTRS, ISNULL(T.RECDPCS,0) AS RECDPCS, ISNULL(T.RECDMTRS,0) AS RECDMTRS, ISNULL(T.PENDINGPCS,0) AS PENDINGPCS, ISNULL(T.PENDINGMTRS,0) AS PENDINGMTRS, SUM(BARCODESTOCK.PCS) AS PCS, SUM(BARCODESTOCK.MTRS) AS MTRS, ISNULL(SUM(BARCODESTOCK.PCS) - T.PENDINGPCS,0)  AS BALPCS, ISNULL(ROUND(SUM(BARCODESTOCK.MTRS) - T.PENDINGMTRS, 2),0) AS BALMTRS, BARCODESTOCK.YEARID ", "", " BARCODESTOCK LEFT OUTER JOIN  (SELECT ITEMNAME, DESIGNNO, SHADE, SUM(PCS) AS ORDERPCS, SUM(MTRS) AS ORDERMTRS, SUM(RECDPCS) AS RECDPCS, SUM(RECDMTRS) AS RECDMTRS, SUM(PENDINGPCS) AS PENDINGPCS,  SUM(PENDINGMTRS) AS PENDINGMTRS, YEARID FROM PENDINGSALEORDER  GROUP BY ITEMNAME, DESIGNNO, SHADE, YEARID) AS T ON BARCODESTOCK.YEARID = T.YEARID AND BARCODESTOCK.COLOR = T.SHADE AND BARCODESTOCK.DESIGNNO = T.DESIGNNO AND  BARCODESTOCK.ITEMNAME = T.ITEMNAME ", WHERECLAUSE & " AND BARCODESTOCK.YEARID = " & YearId & " GROUP BY BARCODESTOCK.ITEMNAME, BARCODESTOCK.DESIGNNO, BARCODESTOCK.COLOR, T.ORDERPCS, T.ORDERMTRS, T.RECDPCS, T.RECDMTRS, T.PENDINGPCS, T.PENDINGMTRS, BARCODESTOCK.YEARID ")
            Dim DT As DataTable = OBJCMN.search("  ALLITEM.ITEMNAME, ALLITEM.CATEGORY, ALLITEM.DESIGNNO, ALLITEM.MILLNAME, ALLITEM.COLOR AS SHADE, ISNULL(T.ORDERPCS, 0) AS ORDERPCS, ISNULL(T.ORDERMTRS, 0) AS ORDERMTRS, ISNULL(T.RECDPCS, 0)  AS RECDPCS, ISNULL(T.RECDMTRS, 0) AS RECDMTRS, ISNULL(T.PENDINGPCS, 0) AS PENDINGPCS, ISNULL(T.PENDINGMTRS, 0) AS PENDINGMTRS, ISNULL(SUM(BSTOCK.PCS),0) AS PCS,  ISNULL(SUM(BSTOCK.MTRS),0) AS MTRS, (ISNULL(SUM(BSTOCK.PCS),0) - ISNULL(T.PENDINGPCS,0)) AS BALPCS, (ROUND(ISNULL(SUM(BSTOCK.MTRS),0) - ISNULL(T.PENDINGMTRS,0), 2)) AS BALMTRS,  ALLITEM.YEARID ", "", " (SELECT DISTINCT ITEMMASTER.item_name AS ITEMNAME, ISNULL(CATEGORYMASTER.CATEGORY_NAME,'') AS CATEGORY, ISNULL(DESIGNMASTER.DESIGN_NO, '') AS DESIGNNO, ISNULL(MILLMASTER.MILL_NAME,'') AS MILLNAME, ISNULL(COLORMASTER.COLOR_name, '') AS COLOR, ITEMMASTER.item_yearid AS YEARID FROM COLORMASTER RIGHT OUTER JOIN DESIGNMASTER_COLOR ON COLORMASTER.COLOR_id = DESIGNMASTER_COLOR.DESIGN_COLORID RIGHT OUTER JOIN ITEMMASTER LEFT OUTER JOIN DESIGNMASTER ON ITEMMASTER.item_id = DESIGNMASTER.DESIGN_ITEMID ON DESIGNMASTER_COLOR.DESIGN_ID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN MILLMASTER ON DESIGNMASTER.DESIGN_MILLID = MILLMASTER.MILL_ID LEFT OUTER JOIN CATEGORYMASTER ON ITEMMASTER.ITEM_CATEGORYID = CATEGORYMASTER.CATEGORY_ID WHERE ITEM_YEARID = " & YearId & ")  AS ALLITEM LEFT OUTER JOIN ( SELECT * FROM  BARCODESTOCK WHERE (BARCODESTOCK.YEARID = " & YearId & ")  " & WHERECLAUSE & ") AS BSTOCK ON ALLITEM.ITEMNAME = BSTOCK.ITEMNAME AND ALLITEM.DESIGNNO = BSTOCK.DESIGNNO AND ALLITEM.COLOR = BSTOCK.COLOR LEFT OUTER JOIN  (SELECT ITEMNAME, DESIGNNO, SHADE, SUM(PCS) AS ORDERPCS, SUM(MTRS) AS ORDERMTRS, SUM(RECDPCS) AS RECDPCS, SUM(RECDMTRS) AS RECDMTRS, SUM(PENDINGPCS)+SUM(OLDPENDINGPCS) AS PENDINGPCS, SUM(PENDINGMTRS)+SUM(OLDPENDINGMTRS) AS PENDINGMTRS, YEARID FROM PENDINGSALEORDER WHERE YEARID = " & YearId & SOCLAUSE & " GROUP BY ITEMNAME, DESIGNNO, SHADE, YEARID) AS T ON ALLITEM.YEARID = T.YEARID AND ALLITEM.COLOR = T.SHADE AND ALLITEM.DESIGNNO = T.DESIGNNO AND ALLITEM.ITEMNAME = T.ITEMNAME  ", " AND ALLITEM.YEARID = " & YearId & " GROUP BY ALLITEM.ITEMNAME, ALLITEM.CATEGORY, ALLITEM.DESIGNNO, ALLITEM.MILLNAME, ALLITEM.COLOR, T.ORDERPCS, T.ORDERMTRS, T.RECDPCS, T.RECDMTRS, T.PENDINGPCS, T.PENDINGMTRS, ALLITEM.YEARID ")
            GRIDBILLDETAILS.DataSource = DT


            'WITH THE ABOVE CODE WE WILL GET ALL THE ITEMS | DESIGN | SHADE PRESENT IN THE MASTERS
            'BUT WE WANT TO REMOVE ALL THOSE DESIGNS WHICH ARE NOT PRESENT IN STOCK (WITH RESPECT TO SHADE)
            'MEANS IF ANY DESIGN HAVE 3 SHADES AND ALL THE 3 SHADES ARE NOT PRESENT IN STOCK, AND WE DONT HAVE ORDER FOR THESE SHADES THEN REMOVE THAT WHOLE DESIGN
            'FOR THIS WE WILL LOOP FOR ALL DESIGN AND SHADES AND CHECK THE ABOVE DATATABLE
            Dim DTDESIGN As DataTable = OBJCMN.search(" DISTINCT ALLITEM.DESIGNNO", "", " (SELECT DISTINCT ITEMMASTER.item_name AS ITEMNAME, ISNULL(CATEGORYMASTER.CATEGORY_NAME,'') AS CATEGORY, ISNULL(DESIGNMASTER.DESIGN_NO, '') AS DESIGNNO, ISNULL(MILLMASTER.MILL_NAME,'') AS MILLNAME, ISNULL(COLORMASTER.COLOR_name, '') AS COLOR, ITEMMASTER.item_yearid AS YEARID FROM COLORMASTER RIGHT OUTER JOIN DESIGNMASTER_COLOR ON COLORMASTER.COLOR_id = DESIGNMASTER_COLOR.DESIGN_COLORID RIGHT OUTER JOIN ITEMMASTER LEFT OUTER JOIN DESIGNMASTER ON ITEMMASTER.item_id = DESIGNMASTER.DESIGN_ITEMID ON DESIGNMASTER_COLOR.DESIGN_ID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN MILLMASTER ON DESIGNMASTER.DESIGN_MILLID = MILLMASTER.MILL_ID LEFT OUTER JOIN CATEGORYMASTER ON ITEMMASTER.ITEM_CATEGORYID = CATEGORYMASTER.CATEGORY_ID WHERE ITEM_YEARID = " & YearId & ")  AS ALLITEM LEFT OUTER JOIN ( SELECT * FROM  BARCODESTOCK WHERE (BARCODESTOCK.YEARID = " & YearId & ")  " & WHERECLAUSE & ") AS BSTOCK ON ALLITEM.ITEMNAME = BSTOCK.ITEMNAME AND ALLITEM.DESIGNNO = BSTOCK.DESIGNNO AND ALLITEM.COLOR = BSTOCK.COLOR LEFT OUTER JOIN  (SELECT ITEMNAME, DESIGNNO, SHADE, SUM(PCS) AS ORDERPCS, SUM(MTRS) AS ORDERMTRS, SUM(RECDPCS) AS RECDPCS, SUM(RECDMTRS) AS RECDMTRS, SUM(PENDINGPCS)+SUM(OLDPENDINGPCS) AS PENDINGPCS, SUM(PENDINGMTRS)+SUM(OLDPENDINGMTRS) AS PENDINGMTRS, YEARID FROM PENDINGSALEORDER WHERE YEARID = " & YearId & SOCLAUSE & " GROUP BY ITEMNAME, DESIGNNO, SHADE, YEARID) AS T ON ALLITEM.YEARID = T.YEARID AND ALLITEM.COLOR = T.SHADE AND ALLITEM.DESIGNNO = T.DESIGNNO AND ALLITEM.ITEMNAME = T.ITEMNAME  ", " AND ALLITEM.YEARID = " & YearId & " GROUP BY ALLITEM.DESIGNNO HAVING ISNULL(SUM(BSTOCK.MTRS),0) = 0 AND ISNULL(SUM(T.ORDERMTRS), 0) = 0 ")
            For Each DESIGNROW As DataRow In DTDESIGN.Rows
                For Each DR As DataRow In DT.Select("DESIGNNO = '" & DESIGNROW("DESIGNNO") & "'")
                    DR.Delete()
                Next
            Next


                If dt.Rows.Count > 0 Then
                GRIDBILL.FocusedRowHandle = GRIDBILL.RowCount - 1
                GRIDBILL.TopRowIndex = GRIDBILL.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub GRIDBILLDETAILS_Click(sender As Object, e As EventArgs) Handles GRIDBILLDETAILS.Click
        Try
            GRIDSTOCKDETAILS.DataSource = Nothing
            GRIDORDERDETAILS.DataSource = Nothing
            If Val(GRIDBILL.GetFocusedRowCellValue("MTRS")) > 0 Then FILLSTOCKGRID()
            If Val(GRIDBILL.GetFocusedRowCellValue("ORDERPCS")) > 0 Then FILLORDERGRID()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub FILLSTOCKGRID()
        Try
            Dim OBJCMN As New ClsCommon
            Dim DT As DataTable = OBJCMN.search("PIECETYPE, UNIT, SUM(PCS) AS PCS, ROUND(SUM(MTRS),2) AS MTRS ", "", " BARCODESTOCK ", WHERECLAUSE & " AND ITEMNAME = '" & GRIDBILL.GetFocusedRowCellValue("ITEMNAME") & "' AND DESIGNNO = '" & GRIDBILL.GetFocusedRowCellValue("DESIGNNO") & "' AND COLOR = '" & GRIDBILL.GetFocusedRowCellValue("SHADE") & "' AND YEARID = " & YearId & " GROUP BY PIECETYPE, UNIT")
            GRIDSTOCKDETAILS.DataSource = DT
            If DT.Rows.Count > 0 Then
                GRIDSTOCK.FocusedRowHandle = GRIDSTOCK.RowCount - 1
                GRIDSTOCK.TopRowIndex = GRIDSTOCK.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub FILLORDERGRID()
        Try
            Dim OBJCMN As New ClsCommon
            Dim DT As DataTable = OBJCMN.search("NAME, ORDERNO, DUEDATE, UNIT, SUM(PENDINGPCS)+SUM(OLDPENDINGPCS) AS PCS, ROUND(SUM(PENDINGMTRS)+SUM(OLDPENDINGMTRS),2) AS MTRS ", "", " PENDINGSALEORDER ", " AND ITEMNAME = '" & GRIDBILL.GetFocusedRowCellValue("ITEMNAME") & "' AND DESIGNNO = '" & GRIDBILL.GetFocusedRowCellValue("DESIGNNO") & "' AND SHADE = '" & GRIDBILL.GetFocusedRowCellValue("SHADE") & "' AND YEARID = " & YearId & SOCLAUSE & " GROUP BY NAME, ORDERNO, DUEDATE, UNIT HAVING ROUND(SUM(PENDINGPCS)+SUM(OLDPENDINGPCS),2) > 0")
            GRIDORDERDETAILS.DataSource = DT
            If DT.Rows.Count > 0 Then
                GRIDORDER.FocusedRowHandle = GRIDSTOCK.RowCount - 1
                GRIDORDER.TopRowIndex = GRIDSTOCK.RowCount - 15
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub SaleOrderVsStockGridReport_Shown(sender As Object, e As EventArgs) Handles Me.Shown
        Try
            If SALEORDERONMTRS = False Then
                GPENDINGMTRS.Visible = False
                GPENDINGPCS.Visible = True
                GPENDINGPCS.VisibleIndex = GBALPCS.VisibleIndex
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub
End Class