
Imports BL

Public Class SelectDesignCardIssue

    Public JOBBERNAME As String = ""
    Public DT As New DataTable
    Public FRMSTRING As String = ""

    Private Sub cmdexit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdexit.Click
        Me.Close()
    End Sub

    Private Sub SelectYarnPO_KeyDown(ByVal sender As Object, ByVal e As System.Windows.Forms.KeyEventArgs) Handles Me.KeyDown
        If e.KeyCode =System.WINDOWS.FORMS.Keys.Escape Then
            Me.Close()
        ElseIf e.KeyCode = Keys.Enter Then
            SendKeys.Send("{Tab}")
        End If
    End Sub

    Private Sub SelectYarnPO_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
        FILLGRID()
    End Sub

    Sub FILLGRID()
        Try
            Cursor.Current = Cursors.WaitCursor

            Dim WHERECLAUSE As String = ""
            If JOBBERNAME <> "" Then WHERECLAUSE = WHERECLAUSE & " AND LEDGERS.ACC_CMPNAME = '" & JOBBERNAME & "'"
            Dim OBJCMN As New ClsCommon()
            Dim dt As New DataTable
            If FRMSTRING = "MRP" Then
                dt = OBJCMN.search(" DESIGNCARDISSUE.CARD_NO AS CARDNO, DESIGNCARDISSUE.CARD_DATE AS DATE, LEDGERS.Acc_cmpname AS NAME, DESIGNCARDISSUE.CARD_TOTALCUT AS TOTALCUT,  DESIGNCARDISSUE.CARD_TOTALMTRS AS TOTALMTRS, DESIGNCARDISSUE.CARD_REMARKS AS REMARKS, DESIGNCARDISSUE_DESC.CARD_GRIDSRNO AS GRIDSRNO, DESIGNMASTER.DESIGN_NO AS DESIGNNO, ISNULL(COLORMASTER.COLOR_name, '') AS MATCHING, DESIGNCARDISSUE_DESC.CARD_CUT AS CUT, DESIGNCARDISSUE_DESC.CARD_WARPTL AS WARPTL, DESIGNCARDISSUE_DESC.CARD_WEFTTL AS WEFTTL, DESIGNCARDISSUE_DESC.CARD_MTRS AS MTRS, DESIGNCARDISSUE_DESC.CARD_SELVEDGE AS SELVEDGE, ISNULL(DESIGNCARDISSUE.CARD_WARPWASTAGE, 0) AS WARPWASTAGE, ISNULL(DESIGNCARDISSUE.CARD_WEFTWASTAGE, 0) AS WEFTWASTAGE, ISNULL(DESIGNCARDISSUE_DESC.CARD_PICKS, 0) AS PICKS, ISNULL(DESIGNCARDISSUE_DESC.CARD_ACTUALPICKS, 0) AS ACTUALPICKS, ISNULL(DESIGNCARDISSUE_DESC.CARD_RATE, 0) AS RATE, ISNULL(DESIGNCARDISSUE_DESC.CARD_BOBBINCHGS, 0) AS BOBBINCHGS, ISNULL(DESIGNCARDISSUE_DESC.CARD_TOTALCHGS, 0) AS TOTALCHGS, ISNULL(DESIGNCARDISSUE_DESC.CARD_OTHERCHGS, 0) AS OTHERCHGS, ISNULL(DESIGNCARDISSUE_DESC.CARD_GRIDDESC, '') AS GRIDDESC, ISNULL(CATEGORYMASTER.category_name, '') AS CATEGORY, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME ", "", " COLORMASTER RIGHT OUTER JOIN CATEGORYMASTER RIGHT OUTER JOIN DESIGNCARDISSUE INNER JOIN DESIGNCARDISSUE_DESC ON DESIGNCARDISSUE.CARD_NO = DESIGNCARDISSUE_DESC.CARD_NO AND DESIGNCARDISSUE.CARD_YEARID = DESIGNCARDISSUE_DESC.CARD_YEARID INNER JOIN LEDGERS ON DESIGNCARDISSUE.CARD_LEDGERID = LEDGERS.Acc_id INNER JOIN DESIGNMASTER ON DESIGNCARDISSUE_DESC.CARD_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN ITEMMASTER ON DESIGNMASTER.DESIGN_ITEMID = ITEMMASTER.item_id ON CATEGORYMASTER.category_id = ITEMMASTER.item_categoryid ON COLORMASTER.COLOR_id = DESIGNCARDISSUE_DESC.CARD_MATCHINGID  ", WHERECLAUSE & " AND DESIGNCARDISSUE.CARD_MRPDONE = 'FALSE' AND DESIGNCARDISSUE.CARD_yearid = " & YearId)
            Else
                dt = OBJCMN.search(" DESIGNCARDISSUE.CARD_NO AS CARDNO, DESIGNCARDISSUE.CARD_DATE AS DATE, LEDGERS.Acc_cmpname AS NAME, DESIGNCARDISSUE.CARD_TOTALCUT AS TOTALCUT,  DESIGNCARDISSUE.CARD_TOTALMTRS AS TOTALMTRS, DESIGNCARDISSUE.CARD_REMARKS AS REMARKS, DESIGNCARDISSUE_DESC.CARD_GRIDSRNO AS GRIDSRNO, DESIGNMASTER.DESIGN_NO AS DESIGNNO, ISNULL(COLORMASTER.COLOR_name, '') AS MATCHING, DESIGNCARDISSUE_DESC.CARD_CUT AS CUT, DESIGNCARDISSUE_DESC.CARD_WARPTL AS WARPTL, DESIGNCARDISSUE_DESC.CARD_WEFTTL AS WEFTTL, DESIGNCARDISSUE_DESC.CARD_MTRS AS MTRS, DESIGNCARDISSUE_DESC.CARD_SELVEDGE AS SELVEDGE, ISNULL(DESIGNCARDISSUE.CARD_WARPWASTAGE, 0) AS WARPWASTAGE, ISNULL(DESIGNCARDISSUE.CARD_WEFTWASTAGE, 0) AS WEFTWASTAGE, ISNULL(DESIGNCARDISSUE_DESC.CARD_PICKS, 0) AS PICKS, ISNULL(DESIGNCARDISSUE_DESC.CARD_ACTUALPICKS, 0) AS ACTUALPICKS, ISNULL(DESIGNCARDISSUE_DESC.CARD_RATE, 0) AS RATE, ISNULL(DESIGNCARDISSUE_DESC.CARD_BOBBINCHGS, 0) AS BOBBINCHGS, ISNULL(DESIGNCARDISSUE_DESC.CARD_TOTALCHGS, 0) AS TOTALCHGS, ISNULL(DESIGNCARDISSUE_DESC.CARD_OTHERCHGS, 0) AS OTHERCHGS, ISNULL(DESIGNCARDISSUE_DESC.CARD_GRIDDESC, '') AS GRIDDESC, ISNULL(CATEGORYMASTER.category_name, '') AS CATEGORY, ISNULL(ITEMMASTER.item_name, '') AS ITEMNAME ", "", " COLORMASTER RIGHT OUTER JOIN CATEGORYMASTER RIGHT OUTER JOIN DESIGNCARDISSUE INNER JOIN DESIGNCARDISSUE_DESC ON DESIGNCARDISSUE.CARD_NO = DESIGNCARDISSUE_DESC.CARD_NO AND DESIGNCARDISSUE.CARD_YEARID = DESIGNCARDISSUE_DESC.CARD_YEARID INNER JOIN LEDGERS ON DESIGNCARDISSUE.CARD_LEDGERID = LEDGERS.Acc_id INNER JOIN DESIGNMASTER ON DESIGNCARDISSUE_DESC.CARD_DESIGNID = DESIGNMASTER.DESIGN_id LEFT OUTER JOIN ITEMMASTER ON DESIGNMASTER.DESIGN_ITEMID = ITEMMASTER.item_id ON CATEGORYMASTER.category_id = ITEMMASTER.item_categoryid ON COLORMASTER.COLOR_id = DESIGNCARDISSUE_DESC.CARD_MATCHINGID  ", WHERECLAUSE & " AND DESIGNCARDISSUE_DESC.CARD_LOOMSMPRECD = 'FALSE' AND DESIGNCARDISSUE.CARD_yearid = " & YearId)
            End If
            gridbilldetails.DataSource = dt
            If dt.Rows.Count > 0 Then
                gridbill.FocusedRowHandle = gridbill.RowCount - 1
                gridbill.TopRowIndex = gridbill.RowCount - 15
            End If
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        Finally
            Cursor.Current = Cursors.Default
        End Try
    End Sub

    Private Sub cmdok_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cmdok.Click
        Try

            DT.Columns.Add("ISSUENO")
            DT.Columns.Add("ISSUESRNO")

            Dim SELECTEDROWS As Int32() = gridbill.GetSelectedRows()
            For I As Integer = 0 To Val(SELECTEDROWS.Length - 1)
                Dim dtrow As DataRow = gridbill.GetDataRow(SELECTEDROWS(I))
                DT.Rows.Add(dtrow("CARDNO"), dtrow("GRIDSRNO"))
            Next
            Me.Close()

        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

    Private Sub gridquotation_CellDoubleClick(ByVal sender As Object, ByVal e As System.Windows.Forms.DataGridViewCellEventArgs)
        Try
            cmdok_Click(sender, e)
        Catch ex As Exception
            If ErrHandle(ex.Message.GetHashCode) = False Then Throw ex
        End Try
    End Sub

End Class