
Imports BL

Public Class HomePage

    Dim OBJCMN As New ClsCommon
    Dim fromD
    Dim toD
    Dim a1, a2, a3, a4 As String
    Dim a11, a12, a13, a14 As String

    Private Sub HomePage_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        Try
            GBRECOUTSTANDING.Visible = RECOUTSTANDTOOLVISIBLE
            GBPJOBORDER.Visible = PENDINGJOTOOLVISIBLE
            GBSALEORDER.Visible = PENDINGSOTOOLVISIBLE
            GBPURORDER.Visible = PENDINGPOTOOLVISIBLE
            GBSTOCK.Visible = STOCKTOOLVISIBLE
            GBYARNSTOCK.Visible = STOCKTOOLVISIBLE

            If RECOUTSTANDTOOLVISIBLE = True Then FILLRECGRID()
            If PENDINGJOTOOLVISIBLE = True Then FILLJO()
            If STOCKTOOLVISIBLE = True Then
                FILLSTOCK()
                FILLYARNSTOCK()
            End If
            If PENDINGSOTOOLVISIBLE = True Then FILLSO()
            If PENDINGPOTOOLVISIBLE = True Then FILLPO()

            If SALEORDERONMTRS = True Then GSOPCS.Caption = "Mtrs"

        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub FILLRECGRID()
        Try
            Dim dt As DataTable = OBJCMN.search(" NAME, (CASE WHEN ROUND(DR,0) > 0 THEN DR ELSE ROUND(CR,0)*-1 END) AS BALANCE ", "", " TRIALBALANCE ", " AND SECONDARY = 'Sundry Debtors' AND (ROUND(DR,0) > 0 OR ROUND(CR,0) > 0) AND YEARID = " & YearId & " ORDER BY NAME")
            GRIDRECDETAILS.DataSource = dt
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub FILLJO()
        Try
            Dim dt As DataTable = OBJCMN.search(" * ", "", " (SELECT YARNDYEINGPROGRAM.PROG_NO AS JONO, YARNDYEINGPROGRAM.PROG_DATE AS JODATE, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(MILLMASTER.MILL_NAME, '') AS MILLNAME, ISNULL(YARNQUALITYMASTER.YARN_NAME, '') AS YARNQUALITY, ISNULL(COLORMASTER.COLOR_name, '') AS SHADE, (YARNDYEINGPROGRAM_DESC.PROG_WT - YARNDYEINGPROGRAM_DESC.PROG_RECDWT) AS QTY, ISNULL(DELIVERYATLEDGERS.Acc_cmpname, '') AS DELIVERYAT  FROM YARNDYEINGPROGRAM_DESC INNER JOIN YARNDYEINGPROGRAM ON YARNDYEINGPROGRAM_DESC.PROG_NO = YARNDYEINGPROGRAM.PROG_NO AND YARNDYEINGPROGRAM_DESC.PROG_YEARID = YARNDYEINGPROGRAM.PROG_YEARID INNER JOIN LEDGERS ON YARNDYEINGPROGRAM.PROG_LEDGERID = LEDGERS.Acc_id INNER JOIN YARNQUALITYMASTER ON YARNDYEINGPROGRAM_DESC.PROG_YARNQUALITYID = YARNQUALITYMASTER.YARN_ID LEFT OUTER JOIN COLORMASTER ON YARNDYEINGPROGRAM_DESC.PROG_SHADEID = COLORMASTER.COLOR_id LEFT OUTER JOIN MILLMASTER ON YARNDYEINGPROGRAM_DESC.PROG_MILLID = MILLMASTER.MILL_ID LEFT OUTER JOIN LEDGERS AS DELIVERYATLEDGERS ON YARNDYEINGPROGRAM_DESC.PROG_GRIDLEDGERID = DELIVERYATLEDGERS.Acc_id  WHERE (YARNDYEINGPROGRAM_DESC.PROG_WT - YARNDYEINGPROGRAM_DESC.PROG_RECDWT > 0) AND (YARNDYEINGPROGRAM_DESC.PROG_CLOSED = 0) AND YARNDYEINGPROGRAM_DESC.PROG_YEARID = " & YearId & " UNION ALL SELECT OPENINGYARNDYEINGPROGRAM.PROG_NO AS JONO, OPENINGYARNDYEINGPROGRAM.PROG_DATE AS JODATE, ISNULL(LEDGERS.Acc_cmpname, '') AS NAME, ISNULL(MILLMASTER.MILL_NAME, '') AS MILLNAME, ISNULL(YARNQUALITYMASTER.YARN_NAME, '') AS YARNQUALITY, ISNULL(COLORMASTER.COLOR_name, '') AS SHADE, (OPENINGYARNDYEINGPROGRAM_DESC.PROG_WT - OPENINGYARNDYEINGPROGRAM_DESC.PROG_RECDWT) AS QTY, ISNULL(DELIVERYATLEDGERS.Acc_cmpname, '') AS DELIVERYAT  FROM OPENINGYARNDYEINGPROGRAM_DESC INNER JOIN OPENINGYARNDYEINGPROGRAM ON OPENINGYARNDYEINGPROGRAM_DESC.PROG_NO = OPENINGYARNDYEINGPROGRAM.PROG_NO AND OPENINGYARNDYEINGPROGRAM_DESC.PROG_YEARID = OPENINGYARNDYEINGPROGRAM.PROG_YEARID INNER JOIN LEDGERS ON OPENINGYARNDYEINGPROGRAM.PROG_LEDGERID = LEDGERS.Acc_id INNER JOIN YARNQUALITYMASTER ON OPENINGYARNDYEINGPROGRAM_DESC.PROG_YARNQUALITYID = YARNQUALITYMASTER.YARN_ID LEFT OUTER JOIN COLORMASTER ON OPENINGYARNDYEINGPROGRAM_DESC.PROG_SHADEID = COLORMASTER.COLOR_id LEFT OUTER JOIN MILLMASTER ON OPENINGYARNDYEINGPROGRAM_DESC.PROG_MILLID = MILLMASTER.MILL_ID LEFT OUTER JOIN LEDGERS AS DELIVERYATLEDGERS ON OPENINGYARNDYEINGPROGRAM_DESC.PROG_GRIDLEDGERID = DELIVERYATLEDGERS.Acc_id  WHERE (OPENINGYARNDYEINGPROGRAM_DESC.PROG_WT - OPENINGYARNDYEINGPROGRAM_DESC.PROG_RECDWT > 0) AND (OPENINGYARNDYEINGPROGRAM_DESC.PROG_CLOSED = 0) AND OPENINGYARNDYEINGPROGRAM_DESC.PROG_YEARID = " & YearId & ") AS T", " ORDER BY T.JONO")
            GRIDJODETAILS.DataSource = dt
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub FILLSTOCK()
        Try
            Dim dt As DataTable = OBJCMN.search(" ITEMNAME, DESIGNNO, SUM(PCS) AS PCS, SUM(MTRS) AS MTRS ", "", " BARCODESTOCK ", " AND YEARID = " & YearId & " GROUP BY ITEMNAME, DESIGNNO")
            GRIDSTOCKDETAILS.DataSource = dt
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub FILLYARNSTOCK()
        Try
            Dim dt As DataTable = OBJCMN.search("  YARNQUALITY, COLOR AS SHADE, MILLNAME, LOTNO, BOXNO, GODOWN, SUM(CONES) AS CONES, SUM(BAGS) AS BAGS, SUM(WT) AS WT", "", " YARNSTOCKVIEW ", " AND YEARID = " & YearId & " GROUP BY YARNQUALITY, COLOR, MILLNAME, LOTNO, BOXNO, GODOWN HAVING SUM(WT) > 0")
            GRIDYARNDETAILS.DataSource = dt
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub FILLSO()
        Try
            Dim DT As New DataTable
            If SALEORDERONMTRS = False Then
                DT = OBJCMN.search("*", "", " (SELECT ISNULL(LEDGERS.Acc_cmpname,'') AS NAME, ISNULL(ITEMMASTER.item_name,'') AS [ITEMNAME], ISNULL(DESIGNMASTER.DESIGN_NO,'') AS DESIGNNO, SUM(SALEORDER_DESC.SO_QTY - SALEORDER_DESC.SO_RECDQTY) AS [PCS] FROM SALEORDER INNER JOIN LEDGERS ON SALEORDER.so_ledgerid = LEDGERS.Acc_id INNER JOIN SALEORDER_DESC ON SALEORDER.so_no = SALEORDER_DESC.SO_NO AND SALEORDER.SO_YEARID = SALEORDER_DESC.SO_YEARID INNER JOIN ITEMMASTER ON SALEORDER_DESC.SO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN DESIGNMASTER ON SALEORDER_DESC.SO_DESIGNID = DESIGN_ID WHERE (SALEORDER_DESC.SO_QTY - SALEORDER_DESC.SO_RECDQTY) > 0 AND SALEORDER_DESC.SO_CLOSED=0  AND SALEORDER.so_YEARID = " & YearId & " GROUP BY ISNULL(LEDGERS.ACC_CMPNAME,''), ISNULL(ITEMMASTER.ITEM_NAME,''), ISNULL(DESIGNMASTER.DESIGN_NO,'')  UNION ALL  SELECT ISNULL(LEDGERS.Acc_cmpname,'') AS NAME, ISNULL(ITEMMASTER.item_name,'') AS [ITEMNAME], ISNULL(DESIGNMASTER.DESIGN_NO,'') AS DESIGNNO, SUM(OPENINGSALEORDER_DESC.OPSO_QTY - OPENINGSALEORDER_DESC.OPSO_RECDQTY) AS [PCS] FROM OPENINGSALEORDER INNER JOIN LEDGERS ON OPENINGSALEORDER.OPSO_ledgerid = LEDGERS.Acc_id INNER JOIN OPENINGSALEORDER_DESC ON OPENINGSALEORDER.OPSO_no = OPENINGSALEORDER_DESC.OPSO_NO AND OPENINGSALEORDER.OPSO_YEARID = OPENINGSALEORDER_DESC.OPSO_YEARID INNER JOIN ITEMMASTER ON OPENINGSALEORDER_DESC.OPSO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN DESIGNMASTER ON OPENINGSALEORDER_DESC.OPSO_DESIGNID = DESIGN_ID WHERE (OPENINGSALEORDER_DESC.OPSO_QTY - OPENINGSALEORDER_DESC.OPSO_RECDQTY) > 0 AND OPENINGSALEORDER_DESC.OPSO_CLOSED=0  AND OPENINGSALEORDER.OPSO_YEARID = " & YearId & " GROUP BY ISNULL(LEDGERS.ACC_CMPNAME,''), ISNULL(ITEMMASTER.ITEM_NAME,''), ISNULL(DESIGNMASTER.DESIGN_NO,'')) AS T", "")
            Else
                DT = OBJCMN.search("*", "", " (SELECT ISNULL(LEDGERS.Acc_cmpname,'') AS NAME, ISNULL(ITEMMASTER.item_name,'') AS [ITEMNAME],  SUM(SALEORDER_DESC.SO_MTRS - SALEORDER_DESC.SO_RECDMTRS) AS [PCS] FROM SALEORDER INNER JOIN LEDGERS ON SALEORDER.so_ledgerid = LEDGERS.Acc_id INNER JOIN SALEORDER_DESC ON SALEORDER.so_no = SALEORDER_DESC.SO_NO AND SALEORDER.SO_YEARID = SALEORDER_DESC.SO_YEARID INNER JOIN ITEMMASTER ON SALEORDER_DESC.SO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN DESIGNMASTER ON SALEORDER_DESC.SO_DESIGNID = DESIGN_ID WHERE ROUND((SALEORDER_DESC.SO_MTRS - SALEORDER_DESC.SO_RECDMTRS),0) > 0 AND SALEORDER_DESC.SO_CLOSED=0  AND SALEORDER.so_YEARID = " & YearId & " GROUP BY ISNULL(LEDGERS.ACC_CMPNAME,''), ISNULL(ITEMMASTER.ITEM_NAME,''), ISNULL(DESIGNMASTER.DESIGN_NO,'') UNION ALL  SELECT ISNULL(LEDGERS.Acc_cmpname,'') AS NAME, ISNULL(ITEMMASTER.item_name,'') AS [ITEMNAME], ISNULL(DESIGNMASTER.DESIGN_NO,'') AS DESIGNNO, SUM(OPENINGSALEORDER_DESC.OPSO_MTRS - OPENINGSALEORDER_DESC.OPSO_RECDMTRS) AS [PCS] FROM OPENINGSALEORDER INNER JOIN LEDGERS ON OPENINGSALEORDER.OPSO_ledgerid = LEDGERS.Acc_id INNER JOIN OPENINGSALEORDER_DESC ON OPENINGSALEORDER.OPSO_no = OPENINGSALEORDER_DESC.OPSO_NO AND OPENINGSALEORDER.OPSO_YEARID = OPENINGSALEORDER_DESC.OPSO_YEARID INNER JOIN ITEMMASTER ON OPENINGSALEORDER_DESC.OPSO_ITEMID = ITEMMASTER.item_id LEFT OUTER JOIN DESIGNMASTER ON OPENINGSALEORDER_DESC.OPSO_DESIGNID = DESIGN_ID WHERE ROUND((OPENINGSALEORDER_DESC.OPSO_MTRS - OPENINGSALEORDER_DESC.OPSO_RECDMTRS),0) > 0 AND OPENINGSALEORDER_DESC.OPSO_CLOSED=0  AND OPENINGSALEORDER.OPSO_YEARID = " & YearId & " GROUP BY ISNULL(LEDGERS.ACC_CMPNAME,''), ISNULL(ITEMMASTER.ITEM_NAME,''), ISNULL(DESIGNMASTER.DESIGN_NO,'')) AS T", "")
            End If
            GRIDSODETAILS.DataSource = DT
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub FILLPO()
        Try
            Dim DT As DataTable = OBJCMN.search("*", "", " (SELECT YARNPURCHASEORDER.YPO_NO AS PONO, YARNPURCHASEORDER.YPO_DATE AS PODATE, LEDGERS.ACC_CMPNAME AS NAME, ISNULL(MILLMASTER.MILL_NAME, '') AS MILLNAME, ISNULL(YARNQUALITYMASTER.YARN_NAME, '') AS YARNQUALITY, ISNULL(COLORMASTER.COLOR_name, '') AS SHADE, SUM(ISNULL((YARNPURCHASEORDER_DESC.YPO_WT - YARNPURCHASEORDER_DESC.YPO_RECDWT), 0)) AS QTY, ISNULL(LEDGERS_1.Acc_cmpname, '') AS DELIVERYAT FROM YARNPURCHASEORDER INNER JOIN YARNPURCHASEORDER_DESC ON YARNPURCHASEORDER.YPO_NO = YARNPURCHASEORDER_DESC.YPO_NO AND YARNPURCHASEORDER.YPO_YEARID = YARNPURCHASEORDER_DESC.YPO_YEARID INNER JOIN LEDGERS ON YARNPURCHASEORDER.YPO_LEDGERID = LEDGERS.Acc_id INNER JOIN YARNQUALITYMASTER ON YARNPURCHASEORDER_DESC.YPO_YARNQUALITYID = YARNQUALITYMASTER.YARN_ID LEFT OUTER JOIN LEDGERS AS LEDGERS_1 ON YARNPURCHASEORDER_DESC.YPO_GRIDLEDGERID = LEDGERS_1.Acc_id LEFT OUTER JOIN COLORMASTER ON YARNPURCHASEORDER_DESC.YPO_SHADEID = COLORMASTER.COLOR_id LEFT OUTER JOIN MILLMASTER ON YARNPURCHASEORDER_DESC.YPO_MILLID = MILLMASTER.MILL_ID WHERE ROUND(YPO_WT - YPO_RECDWT,2) > 0 AND YPO_CLOSED = 0  AND YARNPURCHASEORDER.YPO_YEARID = " & YearId & " GROUP BY YARNPURCHASEORDER.YPO_NO, YARNPURCHASEORDER.YPO_DATE, LEDGERS.ACC_CMPNAME, ISNULL(MILLMASTER.MILL_NAME, ''), ISNULL(YARNQUALITYMASTER.YARN_NAME, ''), ISNULL(COLORMASTER.COLOR_name, ''), ISNULL(LEDGERS_1.Acc_cmpname, '')  UNION ALL  SELECT OPENINGYARNPURCHASEORDER.OYPO_NO AS PONO, OPENINGYARNPURCHASEORDER.OYPO_DATE AS PODATE, LEDGERS.Acc_CMPNAME AS NAME, ISNULL(MILLMASTER.MILL_NAME, '') AS MILLNAME, ISNULL(YARNQUALITYMASTER.YARN_NAME, '') AS YARNQUALITY, ISNULL(COLORMASTER.COLOR_name, '') AS SHADE, SUM(ISNULL((OPENINGYARNPURCHASEORDER_DESC.OYPO_WT- OPENINGYARNPURCHASEORDER_DESC.OYPO_RECDWT), 0)) AS QTY, ISNULL(LEDGERS_1.Acc_cmpname, '') AS DELIVERYAT FROM OPENINGYARNPURCHASEORDER INNER JOIN OPENINGYARNPURCHASEORDER_DESC ON OPENINGYARNPURCHASEORDER.OYPO_NO = OPENINGYARNPURCHASEORDER_DESC.OYPO_NO AND OPENINGYARNPURCHASEORDER.OYPO_YEARID = OPENINGYARNPURCHASEORDER_DESC.OYPO_YEARID INNER JOIN LEDGERS ON OPENINGYARNPURCHASEORDER.OYPO_LEDGERID = LEDGERS.Acc_id INNER JOIN YARNQUALITYMASTER ON OPENINGYARNPURCHASEORDER_DESC.OYPO_YARNQUALITYID = YARNQUALITYMASTER.YARN_ID LEFT OUTER JOIN LEDGERS AS LEDGERS_1 ON OPENINGYARNPURCHASEORDER_DESC.OYPO_GRIDLEDGERID = LEDGERS_1.Acc_id LEFT OUTER JOIN COLORMASTER ON OPENINGYARNPURCHASEORDER_DESC.OYPO_SHADEID = COLORMASTER.COLOR_id LEFT OUTER JOIN MILLMASTER ON OPENINGYARNPURCHASEORDER_DESC.OYPO_MILLID = MILLMASTER.MILL_ID WHERE ROUND(OYPO_WT - OYPO_RECDWT,2) > 0 AND OYPO_CLOSED = 0  AND OPENINGYARNPURCHASEORDER_DESC.OYPO_CLOSED=0  AND OPENINGYARNPURCHASEORDER.OYPO_YEARID = " & YearId & " GROUP BY OPENINGYARNPURCHASEORDER.OYPO_NO, OPENINGYARNPURCHASEORDER.OYPO_DATE, LEDGERS.ACC_CMPNAME, ISNULL(MILLMASTER.MILL_NAME, ''), ISNULL(YARNQUALITYMASTER.YARN_NAME, ''), ISNULL(COLORMASTER.COLOR_name, ''), ISNULL(LEDGERS_1.Acc_cmpname, '')) AS T", "")
            GRIDPODETAILS.DataSource = DT
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub getFromToDate()
        a1 = DatePart(DateInterval.Day, AccFrom.Date)
        a2 = DatePart(DateInterval.Month, AccFrom.Date)
        a3 = DatePart(DateInterval.Year, AccFrom.Date)
        fromD = "(" & a3 & "," & a2 & "," & a1 & ")"

        a11 = DatePart(DateInterval.Day, Now.Date)
        a12 = DatePart(DateInterval.Month, Now.Date)
        a13 = DatePart(DateInterval.Year, Now.Date)
        toD = "(" & a13 & "," & a12 & "," & a11 & ")"
    End Sub

    Sub SHOWRECFORM()
        Try
            If GRIDREC.RowCount > 0 Then
                Dim dtrow As DataRow = GRIDREC.GetFocusedDataRow
                Dim NAME As String = dtrow("NAME")
                If NAME <> "" Then
                    'OPEN OUTSTANDING
                    If ClientName = "YASHVI" Then
                        Dim OBJOUTSTAND As New OutstandingDesign
                        OBJOUTSTAND.MdiParent = MDIMain
                        OBJOUTSTAND.selfor_ss = " {@YEARID}=" & YearId
                        getFromToDate()
                        OBJOUTSTAND.PERIOD = Format(AccFrom.Date, "dd/MM/yyyy") & " - " & Format(Now.Date, "dd/MM/yyyy")
                        OBJOUTSTAND.TODATE = Format(Now.Date, "dd/MM/yyyy")
                        OBJOUTSTAND.selfor_ss = OBJOUTSTAND.selfor_ss & " and {@DATE} <= #" & Format(Now.Date, "MM/dd/yyyy") & "# and {OUTSTANDINGREPORT_DETAILS.BALANCE}>0 and {@NAME}='" & NAME & "'"
                        OBJOUTSTAND.FRMSTRING = "OUTSTANDINGRECDTLS"
                        OBJOUTSTAND.DAYS = "DUEDATE"
                        OBJOUTSTAND.ADDRESS = 0
                        OBJOUTSTAND.SHOWPRINTDATE = 1
                        OBJOUTSTAND.SHOWREMARKS = 0
                        OBJOUTSTAND.Show()

                    ElseIf ClientName = "AVIS" Then
                        Dim OBJOUTSTAND As New RecOutstanding
                        OBJOUTSTAND.MdiParent = MDIMain
                        OBJOUTSTAND.PARTYNAME = NAME
                        OBJOUTSTAND.Show()

                    Else
                        Dim objlb As New RegisterDetails
                        objlb.TEMPNAME = NAME
                        objlb.MdiParent = MDIMain
                        objlb.Show()
                    End If
                End If
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub SHOWYARNSTOCKDETAILS()
        Try
            If GRIDYARN.RowCount > 0 Then
                Dim dtrow As DataRow = GRIDYARN.GetFocusedDataRow
                Dim OBJYARN As New YarnOnHandStock
                OBJYARN.MdiParent = MDIMain
                OBJYARN.WHERECLAUSE = " AND YARNQUALITY = '" & dtrow("YARNQUALITY") & "' AND COLOR = '" & dtrow("SHADE") & "'"
                OBJYARN.Show()
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub SHOWSTOCKDETAILS()
        Try
            If GRIDSTOCK.RowCount > 0 Then
                Dim dtrow As DataRow = GRIDSTOCK.GetFocusedDataRow
                Dim ITEMNAME As String = dtrow("ITEMNAME")
                If ITEMNAME <> "" Then
                    If ALLOWBARCODEPRINT = True Then
                        Dim OBJSTOCK As New GodownwiseDetails
                        OBJSTOCK.TEMPITEMNAME = ITEMNAME
                        OBJSTOCK.TEMPDESIGNNO = dtrow("DESIGNNO")
                        OBJSTOCK.MdiParent = MDIMain
                        OBJSTOCK.Show()
                    Else
                        Dim OBJSTOCK As New StockDesign
                        OBJSTOCK.MdiParent = MDIMain
                        OBJSTOCK.WHERECLAUSE = " {STOCKREGISTER.YEARID}=" & YearId & " and {STOCKREGISTER.ITEMNAME}='" & ITEMNAME & "'"
                        OBJSTOCK.FRMSTRING = "ITEMSTOCKSUMM"
                        OBJSTOCK.FROMDATE = AccFrom.Date
                        OBJSTOCK.TODATE = AccTo.Date
                        OBJSTOCK.Show()
                    End If
                End If
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub GRIDREC_DoubleClick(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles GRIDREC.DoubleClick
        Try
            SHOWRECFORM()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub GRIDSTOCK_DoubleClick(sender As Object, e As EventArgs) Handles GRIDSTOCK.DoubleClick
        Try
            SHOWSTOCKDETAILS()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub GRIDSO_DoubleClick(sender As Object, e As EventArgs) Handles GRIDSO.DoubleClick
        Try
            SHOWSOPO("SO")
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub GRIDPO_DoubleClick(sender As Object, e As EventArgs) Handles GRIDPO.DoubleClick
        Try
            If GRIDPO.RowCount > 0 Then
                Dim dtrow As DataRow = GRIDPO.GetFocusedDataRow
                Dim OBJPO As New YarnPurchaseOrder
                OBJPO.MdiParent = MDIMain
                OBJPO.tempono = Val(dtrow("PONO"))
                OBJPO.EDIT = True
                OBJPO.Show()
            End If
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Sub SHOWSOPO(FRMSTRING As String)
        Try
            Dim OBJGRN As New SaleInvoiceDesign
            OBJGRN.MdiParent = MDIMain
            OBJGRN.PERIOD = Format(AccFrom, "dd/MM/yyyy") & " - " & Format(AccTo, "dd/MM/yyyy")
            OBJGRN.PENDINGSO = "PENDING"
            OBJGRN.POSOFRMSTRING = FRMSTRING

            If FRMSTRING = "SO" Then
                OBJGRN.WHERECLAUSE = " {ALLSALEORDER.SO_yearid}=" & YearId
                OBJGRN.WHERECLAUSE = OBJGRN.WHERECLAUSE & " and {LEDGERS.ACC_CMPNAME}='" & GRIDSO.GetFocusedRowCellValue("NAME") & "'"
                OBJGRN.WHERECLAUSE = OBJGRN.WHERECLAUSE & " and {ITEMMASTER.ITEM_NAME}='" & GRIDSO.GetFocusedRowCellValue("ITEMNAME") & "'"
                OBJGRN.FRMSTRING = "SOSTATUS"
                OBJGRN.WHERECLAUSE = OBJGRN.WHERECLAUSE & " and {@BALANCE} > 0 and {ALLSALEORDER_DESC.SO_Closed}=FALSE "
            Else
                OBJGRN.WHERECLAUSE = " {ALLPURCHASEORDER.PO_yearid}=" & YearId
                OBJGRN.WHERECLAUSE = OBJGRN.WHERECLAUSE & " and {LEDGERS.ACC_CMPNAME}='" & GRIDPO.GetFocusedRowCellValue("NAME") & "'"
                OBJGRN.WHERECLAUSE = OBJGRN.WHERECLAUSE & " and {ITEMMASTER.ITEM_NAME}='" & GRIDPO.GetFocusedRowCellValue("ITEMNAME") & "'"
                OBJGRN.FRMSTRING = "POSTATUS"
                OBJGRN.WHERECLAUSE = OBJGRN.WHERECLAUSE & " and {@BALANCE} > 0 and {ALLPURCHASEORDER_DESC.PO_Closed}=FALSE "
            End If

            OBJGRN.Show()

        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub GRIDYARN_DoubleClick(sender As Object, e As EventArgs) Handles GRIDYARN.DoubleClick
        Try
            SHOWYARNSTOCKDETAILS()
        Catch ex As Exception
            Throw ex
        End Try
    End Sub

    Private Sub GRIDJO_DoubleClick(sender As Object, e As EventArgs) Handles GRIDJO.DoubleClick
        Try
            If GRIDJO.RowCount > 0 Then
                Dim dtrow As DataRow = GRIDJO.GetFocusedDataRow
                Dim OBJJO As New YarnDyeingProgram
                OBJJO.MdiParent = MDIMain
                OBJJO.TEMPPROGNO = Val(dtrow("JONO"))
                OBJJO.EDIT = True
                OBJJO.Show()
            End If

        Catch ex As Exception
            Throw ex
        End Try
    End Sub
End Class