<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>
Partial Class SaleReturn
    Inherits System.Windows.Forms.Form

    Friend WithEvents EP As ErrorProvider
    Private components As System.ComponentModel.IContainer
    Friend WithEvents BlendPanel1 As VbPowerPack.BlendPanel
    Friend WithEvents TXTSRCHNO As TextBox
    Friend WithEvents Label27 As Label
    Friend WithEvents CMDSELECTCHALLAN As Button
    Friend WithEvents TXTTOTALWITHGST As TextBox
    Friend WithEvents CHKTCS As CheckBox
    Friend WithEvents TXTTCSPER As TextBox
    Friend WithEvents TXTTCSAMT As TextBox
    Friend WithEvents DTACTUALINVDATE As DateTimePicker
    Friend WithEvents Label24 As Label
    Friend WithEvents TXTACTUALINVNO As TextBox
    Friend WithEvents Label26 As Label
    Friend WithEvents TXTTO As TextBox
    Friend WithEvents LBLTO As Label
    Friend WithEvents LBLFROM As Label
    Friend WithEvents TXTFROM As TextBox
    Friend WithEvents LBLCATEGORY As Label
    Friend WithEvents LBLPACKING As Label
    Friend WithEvents CMBPACKING As ComboBox
    Friend WithEvents CMBDEBITLEDGER As ComboBox
    Friend WithEvents Label23 As Label
    Friend WithEvents Label22 As Label
    Friend WithEvents Label20 As Label
    Friend WithEvents TXTPARTYREFNO As TextBox
    Friend WithEvents TXTINVINITIALS As TextBox
    Friend WithEvents Label15 As Label
    Friend WithEvents CMBAGENT As ComboBox
    Friend WithEvents TXTEWAYBILLNO As TextBox
    Friend WithEvents Label14 As Label
    Friend WithEvents CHKMANUAL As CheckBox
    Friend WithEvents TXTINVTYPE As TextBox
    Friend WithEvents Label13 As Label
    Friend WithEvents TXTINVREGNAME As TextBox
    Friend WithEvents Label5 As Label
    Friend WithEvents TXTTRANSADD As TextBox
    Friend WithEvents TXTWT As TextBox
    Friend WithEvents Label39 As Label
    Friend WithEvents txtinwords As TextBox
    Friend WithEvents Label29 As Label
    Friend WithEvents TXTSTATECODE As TextBox
    Friend WithEvents LBLIGST As Label
    Friend WithEvents LBLSGST As Label
    Friend WithEvents LBLCGST As Label
    Friend WithEvents TXTIGSTPER As TextBox
    Friend WithEvents TXTSGSTPER As TextBox
    Friend WithEvents TXTCGSTPER As TextBox
    Friend WithEvents TXTIGSTAMT As TextBox
    Friend WithEvents TXTSGSTAMT As TextBox
    Friend WithEvents TXTCGSTAMT As TextBox
    Friend WithEvents Label19 As Label
    Friend WithEvents TXTSUBTOTAL As TextBox
    Friend WithEvents Label16 As Label
    Friend WithEvents Label38 As Label
    Friend WithEvents TXTCHARGES As TextBox
    Friend WithEvents txtroundoff As TextBox
    Friend WithEvents TXTGRANDTOTAL As TextBox
    Friend WithEvents Label36 As Label
    Friend WithEvents txtbillamt As TextBox
    Friend WithEvents Label7 As Label
    Friend WithEvents INVDATE As DateTimePicker
    Friend WithEvents Label3 As Label
    Friend WithEvents TXTINVNO As TextBox
    Friend WithEvents Label4 As Label
    Friend WithEvents SALRETDATE As MaskedTextBox
    Friend WithEvents LBLTOTALAMT As Label
    Friend WithEvents CMDSELECTRET As Button
    Friend WithEvents TabControl1 As TabControl
    Friend WithEvents CHALLANDATE As DateTimePicker
    Friend WithEvents Label9 As Label
    Friend WithEvents TXTCHALLANNO As TextBox
    Friend WithEvents Label11 As Label
    Friend WithEvents TXTBARCODE As TextBox
    Friend WithEvents Label1 As Label
    Friend WithEvents cmbGodown As ComboBox
    Friend WithEvents LBLTOTALWT As Label
    Friend WithEvents CMBCODE As ComboBox
    Friend WithEvents GroupBox1 As GroupBox
    Friend WithEvents LBLTOTALMTRS As Label
    Friend WithEvents txtadd As TextBox
    Friend WithEvents Label10 As Label
    Friend WithEvents PBlock As PictureBox
    Friend WithEvents cmddelete As Button
    Friend WithEvents lbltotalqty As Label
    Friend WithEvents cmdclear As Button
    Friend WithEvents cmdok As Button
    Friend WithEvents cmdexit As Button
    Friend WithEvents TXTSALRETNO As TextBox
    Friend WithEvents Label12 As Label
    Friend WithEvents lblgrndate As Label
    Friend WithEvents GroupBox5 As GroupBox
    Friend WithEvents tstxtbillno As TextBox
    Friend WithEvents lbllocked As Label
    Friend WithEvents Label6 As Label
    Friend WithEvents CMBNAME As ComboBox
    Friend WithEvents Label2 As Label
    Friend WithEvents ToolStrip1 As ToolStrip
    Friend WithEvents OpenFileDialog1 As OpenFileDialog
    Friend WithEvents TabPage1 As TabPage
    Friend WithEvents GRIDSALRET As DataGridView
    Friend WithEvents gsrno As DataGridViewTextBoxColumn
    Friend WithEvents GPIECETYPE As DataGridViewTextBoxColumn
    Friend WithEvents gitemname As DataGridViewTextBoxColumn
    Friend WithEvents GHSNCODE As DataGridViewTextBoxColumn
    Friend WithEvents GQUALITY As DataGridViewTextBoxColumn
    Friend WithEvents GDESIGN As DataGridViewTextBoxColumn
    Friend WithEvents gcolor As DataGridViewTextBoxColumn
    Friend WithEvents GBALENO As DataGridViewTextBoxColumn
    Friend WithEvents gcut As DataGridViewTextBoxColumn
    Friend WithEvents GWT As DataGridViewTextBoxColumn
    Friend WithEvents gQty As DataGridViewTextBoxColumn
    Friend WithEvents gqtyunit As DataGridViewTextBoxColumn
    Friend WithEvents GMTRS As DataGridViewTextBoxColumn
    Friend WithEvents GRATE As DataGridViewTextBoxColumn
    Friend WithEvents GPER As DataGridViewTextBoxColumn
    Friend WithEvents GAMT As DataGridViewTextBoxColumn
    Friend WithEvents GRACK As DataGridViewTextBoxColumn
    Friend WithEvents GSHELF As DataGridViewTextBoxColumn
    Friend WithEvents GBARCODE As DataGridViewTextBoxColumn
    Friend WithEvents GGDNBARCODE As DataGridViewTextBoxColumn
    Friend WithEvents GDONE As DataGridViewTextBoxColumn
    Friend WithEvents GOUTPCS As DataGridViewTextBoxColumn
    Friend WithEvents GOUTMTRS As DataGridViewTextBoxColumn
    Friend WithEvents GFROMNO As DataGridViewTextBoxColumn
    Friend WithEvents GFROMSRNO As DataGridViewTextBoxColumn
    Friend WithEvents TXTBALENO As TextBox
    Friend WithEvents CMBPER As ComboBox
    Friend WithEvents TXTHSNCODE As TextBox
    Friend WithEvents CMBSHELF As ComboBox
    Friend WithEvents CMBRACK As ComboBox
    Friend WithEvents TXTRATE As TextBox
    Friend WithEvents TXTAMT As TextBox
    Friend WithEvents CMBPIECETYPE As ComboBox
    Friend WithEvents CMBDESIGN As ComboBox
    Friend WithEvents TXTCUT As TextBox
    Friend WithEvents CMBQUALITY As ComboBox
    Friend WithEvents cmbitemname As ComboBox
    Friend WithEvents cmbqtyunit As ComboBox
    Friend WithEvents txtsrno As TextBox
    Friend WithEvents txtqty As TextBox
    Friend WithEvents TXTMTRS As TextBox
    Friend WithEvents cmbcolor As ComboBox
    Friend WithEvents TBEXTRACHGS As TabPage
    Friend WithEvents TXTNETT As TextBox
    Friend WithEvents Label25 As Label
    Friend WithEvents TXTTAXID As TextBox
    Friend WithEvents TXTCHGSPER As TextBox
    Friend WithEvents GRIDCHGS As DataGridView
    Friend WithEvents ESRNO As DataGridViewTextBoxColumn
    Friend WithEvents ECHARGES As DataGridViewTextBoxColumn
    Friend WithEvents EPER As DataGridViewTextBoxColumn
    Friend WithEvents EAMT As DataGridViewTextBoxColumn
    Friend WithEvents ETAXID As DataGridViewTextBoxColumn
    Friend WithEvents TXTCHGSAMT As TextBox
    Friend WithEvents TXTCHGSSRNO As TextBox
    Friend WithEvents CMBCHARGES As ComboBox
    Friend WithEvents TXTGSTIN As TextBox
    Friend WithEvents Label30 As Label
    Friend WithEvents tbupload As TabPage
    Friend WithEvents CMDVIEW As Button
    Friend WithEvents TXTNEWIMGPATH As TextBox
    Friend WithEvents TXTFILENAME As TextBox
    Friend WithEvents txtimgpath As TextBox
    Friend WithEvents cmdupload As Button
    Friend WithEvents txtuploadname As TextBox
    Friend WithEvents txtuploadsrno As TextBox
    Friend WithEvents txtuploadremarks As TextBox
    Friend WithEvents gridupload As DataGridView
    Friend WithEvents GGRIDUPLOADSRNO As DataGridViewTextBoxColumn
    Friend WithEvents GREMARKS As DataGridViewTextBoxColumn
    Friend WithEvents GNAME As DataGridViewTextBoxColumn
    Friend WithEvents GIMGPATH As DataGridViewTextBoxColumn
    Friend WithEvents GNEWIMGPATH As DataGridViewTextBoxColumn
    Friend WithEvents GFILENAME As DataGridViewTextBoxColumn
    Friend WithEvents Label8 As Label
    Friend WithEvents PBSoftCopy As PictureBox
    Friend WithEvents TBADJUSTMENT As TabPage
    Friend WithEvents TXTBILLREMARKS As TextBox
    Friend WithEvents LBLBILLTOTAL As Label
    Friend WithEvents Label32 As Label
    Friend WithEvents TXTINVTOTAL As TextBox
    Friend WithEvents Label31 As Label
    Friend WithEvents TXTCHQBAL As TextBox
    Friend WithEvents Label28 As Label
    Friend WithEvents TXTADJTOTAL As TextBox
    Friend WithEvents TXTNARR As TextBox
    Friend WithEvents CMBBILLNO As ComboBox
    Friend WithEvents CMBPAYTYPE As ComboBox
    Friend WithEvents TXTADJAMT As TextBox
    Friend WithEvents GRIDPAYMENT As DataGridView
    Friend WithEvents GADJSRNO As DataGridViewTextBoxColumn
    Friend WithEvents gpaytype As DataGridViewTextBoxColumn
    Friend WithEvents gbillno As DataGridViewTextBoxColumn
    Friend WithEvents gdesc As DataGridViewTextBoxColumn
    Friend WithEvents GADJAMT As DataGridViewTextBoxColumn
    Friend WithEvents GAMTPAID As DataGridViewTextBoxColumn
    Friend WithEvents GEXTRAAMT As DataGridViewTextBoxColumn
    Friend WithEvents GRETURN As DataGridViewTextBoxColumn
    Friend WithEvents GBALANCE As DataGridViewTextBoxColumn
    Friend WithEvents TXTADJSRNO As TextBox
    Friend WithEvents GRIDBILL As DataGridView
    Friend WithEvents lrdate As DateTimePicker
    Friend WithEvents Label17 As Label
    Friend WithEvents cmbtrans As ComboBox
    Friend WithEvents Label18 As Label
    Friend WithEvents txtlrno As TextBox
    Friend WithEvents Label21 As Label
    Friend WithEvents txtremarks As TextBox
    Friend WithEvents OpenToolStripButton As ToolStripButton
    Friend WithEvents SaveToolStripButton As ToolStripButton
    Friend WithEvents PrintToolStripButton As ToolStripButton
    Friend WithEvents tooldelete As ToolStripButton
    Friend WithEvents toolStripSeparator As ToolStripSeparator
    Friend WithEvents toolprevious As ToolStripButton
    Friend WithEvents toolnext As ToolStripButton
    Friend WithEvents ToolStripSeparator1 As ToolStripSeparator
    Friend WithEvents ACKDATE As DateTimePicker
    Friend WithEvents Label56 As Label
    Friend WithEvents TXTACKNO As TextBox
    Friend WithEvents Label58 As Label
    Friend WithEvents CMDGETQRCODE As Button
    Friend WithEvents PBQRCODE As PictureBox
    Friend WithEvents CMDUPLOADIRN As Button
    Friend WithEvents Label53 As Label
    Friend WithEvents TXTIRNNO As TextBox
    Friend WithEvents TOOLEINV As ToolStripButton
End Class
